export type Issue =
  |'SCHLAGLOCH'
  |'SCHLECHTER_STRASSENBELAG'
  |'BEWUCHS'
  | 'FEHLENDE_BESCHILDERUNG'
  | 'FALSCHE_BESCHILDERUNG'
  | 'POLLER_HINDERNIS'
  | 'UNKLARE_MARKIERUNG'
  | 'UNEBENHEITEN_BODENWELLEN'
  | 'KEINE_KATEGORIE'
    ;
